<?php

use Illuminate\Support\Facades\Http;
use Illuminate\Support\HtmlString;

/*This method get vite assets display with asset
|*according to the environment(local or production)
|*/
function vite_assets()
{
    $devServerIsRunning = false;
    if (app()->environment('local')) {
        try {
            Http::get("http://127.0.0.1:5173");
            $devServerIsRunning = true;
        } catch (Exception $e) {
            error_log($e);
        }
    }

    //If dev server of vite is running we return assets generated by vite
    if ($devServerIsRunning) {
        return view("vite-asset.vite");
    }

    /*If dev server of vite is off or if we are in production we
    |*get manifest.json data an we get asset generated path.
    |*Vite build asset is locate in public/build/
     */

    $manifest = json_decode(file_get_contents(
        public_path('build/manifest.json')
    ), true);

    $appJS = asset("build/".$manifest['resources/js/app.js']['file']);
    $appCSS = asset("build/".$manifest['resources/css/app.css']['file']);
    $appSCSS = asset("build/".$manifest['resources/scss/app.scss']['file']);

    return new HtmlString(<<<HTML
        <script type="module" src="{$appJS}"></script>
        <link rel="stylesheet" href="{$appCSS}">
        <link rel="stylesheet" href="{$appSCSS}">
    HTML);
}
